# Logistic Regression

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [4]:
dataset = pd.read_csv('MeritRank.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(X_train)

[[    23  20000]
 [    30   1120]
 [    27  84000]
 [    35  44000]
 [    30  80000]
 [    34     30]
 [    27  20000]
 [    26  17000]
 [    31   1890]
 [    30 116000]
 [    18  44000]
 [    47   3000]
 [    46   2800]
 [    23  48000]
 [    32   1230]
 [    33 113000]
 [    35   2000]
 [    25  87000]
 [    35 108000]
 [    33  51000]
 [    19   1222]
 [    29  80000]
 [    45   2600]
 [    27  17000]
 [    26  72000]
 [    27   1222]
 [    28  85000]
 [    32 117000]
 [    19   1000]
 [    27  90000]
 [    29  43000]
 [    24  32000]
 [    26   5200]
 [    35  27000]
 [    45   2200]
 [    29  83000]
 [    26    800]
 [    27   1330]
 [    35  50000]
 [    28  79000]
 [    18  52000]
 [    21  16000]
 [    20  49000]
 [    18  82000]
 [    32  18000]
 [    48   2900]
 [    31  18000]
 [    31  89000]
 [    29  28000]
 [    29  83000]
 [    31  68000]
 [    45   2200]
 [    22  81000]
 [    20  23000]
 [    22  27000]
 [    47   2000]
 [    30  49000]
 [    25  79000]
 [    27  3100

In [7]:
print(y_train)

[0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1 0 1
 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0]


In [8]:
print(X_test)

[[    49   2800]
 [    30  62000]
 [    26   1111]
 [    24  55000]
 [    22  63000]
 [    39  42000]
 [    47   2500]
 [    28  87000]
 [    27  58000]
 [    24  19000]
 [    35  23000]
 [    26  81000]
 [    24  27000]
 [    32  18000]
 [    32 150000]
 [    31  74000]
 [    48   4100]
 [    46   2300]
 [    28  44000]
 [    25   3300]
 [    30  15000]
 [    23  66000]
 [    27   1232]
 [    24  55000]]


In [9]:
print(y_test)

[1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0]


## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[-0.83620398 -0.61468129]
 [ 0.01177752 -1.13789423]
 [-0.35164312  1.15892189]
 [ 0.61747859  0.05041991]
 [ 0.01177752  1.0480717 ]
 [ 0.49633838 -1.16810091]
 [-0.35164312 -0.61468129]
 [-0.47278334 -0.69781894]
 [ 0.13291774 -1.11655556]
 [ 0.01177752  2.04572349]
 [-1.44190505  0.05041991]
 [ 2.07116116 -1.08579463]
 [ 1.95002095 -1.09133714]
 [-0.83620398  0.1612701 ]
 [ 0.25405795 -1.13484585]
 [ 0.37519816  1.96258584]
 [ 0.61747859 -1.11350718]
 [-0.59392355  1.24205954]
 [ 0.61747859  1.82402309]
 [ 0.37519816  0.24440775]
 [-1.32076484 -1.13506755]
 [-0.10936269  1.0480717 ]
 [ 1.82888074 -1.09687965]
 [-0.35164312 -0.69781894]
 [-0.47278334  0.8263713 ]
 [-0.35164312 -1.13506755]
 [-0.23050291  1.18663444]
 [ 0.25405795  2.07343604]
 [-1.32076484 -1.14121973]
 [-0.35164312  1.32519719]
 [-0.10936269  0.02270736]
 [-0.71506377 -0.28213069]
 [-0.47278334 -1.02482702]
 [ 0.61747859 -0.42069344]
 [ 1.82888074 -1.10796467]
 [-0.10936269  1.13120934]
 [-0.47278334 -1.14676224]
 

In [12]:
print(X_test)

[[ 2.31344159 -1.09133714]
 [ 0.01177752  0.5492458 ]
 [-0.47278334 -1.13814364]
 [-0.71506377  0.35525795]
 [-0.95734419  0.57695835]
 [ 1.10203945 -0.00500519]
 [ 2.07116116 -1.09965091]
 [-0.23050291  1.24205954]
 [-0.35164312  0.4383956 ]
 [-0.71506377 -0.64239384]
 [ 0.61747859 -0.53154364]
 [-0.47278334  1.07578425]
 [-0.71506377 -0.42069344]
 [ 0.25405795 -0.67010639]
 [ 0.25405795  2.98795018]
 [ 0.13291774  0.8817964 ]
 [ 2.19230138 -1.05531083]
 [ 1.95002095 -1.10519342]
 [-0.23050291  0.05041991]
 [-0.59392355 -1.07748087]
 [ 0.01177752 -0.75324404]
 [-0.83620398  0.660096  ]
 [-0.35164312 -1.13479042]
 [-0.71506377  0.35525795]]


## Training the Logistic Regression model on the Training set

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting a new result

In [14]:
print(classifier.predict(sc.transform([[30,87000]])))

[0]


## Predicting the Test set results

In [15]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]]


## Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[16  0]
 [ 1  7]]


0.9583333333333334

## Visualising the Training set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

## Visualising the Test set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()