In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
data=pd.read_csv('data.csv')
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [33]:
dep=data.iloc[:,-1:].values
ind=data.iloc[:,0:3].values

In [34]:
from sklearn.impute import SimpleImputer

In [35]:
missing=SimpleImputer(missing_values=np.nan,strategy='mean')
missing.fit(ind[:,1:3])
ind[:,1:3]=missing.transform(ind[:,1:3])
print(ind)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [36]:
from sklearn.compose import  ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
ind=np.array(ct.fit_transform(ind))
print(ind)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [42]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
dep=l.fit_transform(dep)
print(dep)

[0 1 0 0 1 1 0 1 0 1]


In [54]:
dataset=pd.read_csv('Global_Superstore2.csv')
dep1=dataset.iloc[:,-1:].values
ind1=dataset.iloc[:,21:23].values

In [55]:
missing1=SimpleImputer(missing_values=np.nan,strategy='mean')
missing1.fit(ind1[:,:])
ind1[:,:]=missing1.transform(ind1[:,:])
print(ind1)

[[ 7.621845e+02  9.335700e+02]
 [-2.887650e+02  9.236300e+02]
 [ 9.199710e+02  9.154900e+02]
 ...
 [ 1.123080e+01  1.000000e-02]
 [ 2.400000e+00  0.000000e+00]
 [ 1.800000e+00  0.000000e+00]]


In [63]:
l1=LabelEncoder()
dep1=l1.fit_transform(dep1)
print(dep1)
print(ind1)

[0 0 3 ... 1 3 1]
[[ 7.621845e+02  9.335700e+02]
 [-2.887650e+02  9.236300e+02]
 [ 9.199710e+02  9.154900e+02]
 ...
 [ 1.123080e+01  1.000000e-02]
 [ 2.400000e+00  0.000000e+00]
 [ 1.800000e+00  0.000000e+00]]


In [82]:
demographic=pd.read_csv('demographic.csv')
ind2=demographic.iloc[:,-1:].values
print(ind2)
ct2=ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
ind2=np.array(ct2.fit_transform(ind2))
print(ind2)

[['High income']
 ['Low income']
 ['Upper middle income']
 ['Upper middle income']
 ['High income']
 ['High income']
 ['Lower middle income']
 ['High income']
 ['High income']
 ['High income']
 ['Upper middle income']
 ['Low income']
 ['High income']
 ['Low income']
 ['Low income']
 ['Lower middle income']
 ['Upper middle income']
 ['High income']
 ['High income']
 ['Upper middle income']
 ['Upper middle income']
 ['Upper middle income']
 ['High income']
 ['Lower middle income']
 ['Upper middle income']
 ['High income']
 ['High income']
 ['Lower middle income']
 ['Upper middle income']
 ['Low income']
 ['High income']
 ['High income']
 ['High income']
 ['Upper middle income']
 ['Lower middle income']
 ['Lower middle income']
 ['Lower middle income']
 ['Upper middle income']
 ['Low income']
 ['Lower middle income']
 ['Upper middle income']
 ['Upper middle income']
 ['High income']
 ['High income']
 ['High income']
 ['High income']
 ['Lower middle income']
 ['High income']
 ['Upper middl