In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('NSE-TATA.csv')
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -1].values
print(X)
print(y)



[[208.   222.25 206.85 216.   215.15]
 [217.   218.6  205.9  210.25 209.2 ]
 [223.5  227.8  216.15 217.25 218.2 ]
 ...
 [156.   160.8  155.85 160.3  160.15]
 [155.7  158.2  154.15 155.3  155.55]
 [157.   157.8  155.2  155.8  155.8 ]]
[10062.83  7407.06  3815.79 ...  4978.8   3204.49  2688.94]


In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
print(X_train)

[[159.25 159.8  153.5  154.2  154.75]
 [148.   151.7  147.1  150.5  150.65]
 [128.   129.   126.25 127.75 128.  ]
 ...
 [164.   169.9  161.55 168.3  167.7 ]
 [134.25 136.15 133.2  133.75 133.9 ]
 [147.   148.   144.2  146.5  146.2 ]]


In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :-1] = sc.fit_transform(X_train[:, :-1])
X_test[:, :-1] = sc.transform(X_test[:, :-1])

In [4]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [5]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[  997.33  1901.94]
 [ 7762.71  4544.83]
 [ 4331.7   8238.83]
 [ 6958.79  4303.91]
 [ 3204.49  2178.49]
 [ 2183.57  1729.  ]
 [ 1750.14  4105.11]
 [ 2561.91  1811.73]
 [32325.56  9934.06]
 [  777.45   765.29]
 [ 7147.52 55755.08]
 [ 4845.26 10330.87]
 [ 4289.35  7162.35]
 [ 2443.6   2738.14]
 [ 1647.     873.85]
 [ 6674.93  2742.84]
 [21586.26  6855.32]
 [ 1165.48  3060.59]
 [ 1794.94  4119.2 ]
 [ 8975.77  7022.82]
 [ 4448.8   3454.22]
 [ 4964.89  3091.19]
 [ 4476.22  3695.01]
 [ 1662.47  3171.42]
 [ 3211.22  7005.22]
 [ 2742.65  2322.75]
 [15781.35  8566.75]
 [15130.67  4536.3 ]
 [ 3938.54  1714.3 ]
 [ 3358.75  4978.8 ]
 [ 3695.88  6001.16]
 [ 4746.09  7111.7 ]
 [ 8039.92  3600.42]
 [12811.25  7052.02]
 [  970.86  1487.76]
 [ 2960.86  4600.91]
 [ 3285.91  1633.27]
 [ 1916.53  3586.44]
 [ 7205.7   3674.2 ]
 [  771.53  2844.74]
 [ 6958.79  3157.09]
 [ 1708.02  1635.01]
 [ 8804.57  4706.54]
 [ 9025.87  5479.6 ]
 [  976.55  2444.39]
 [ 1905.12  2738.72]
 [ 4032.28  4118.57]
 [ 2462.36  2

In [6]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.010383597406375289