In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('NSE-TATA.csv')
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[208.   222.25 206.85 216.   215.15]
 [217.   218.6  205.9  210.25 209.2 ]
 [223.5  227.8  216.15 217.25 218.2 ]
 ...
 [156.   160.8  155.85 160.3  160.15]
 [155.7  158.2  154.15 155.3  155.55]
 [157.   157.8  155.2  155.8  155.8 ]]
[10062.83  7407.06  3815.79 ...  4978.8   3204.49  2688.94]


In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
print(X_train)

[[159.25 159.8  153.5  154.2  154.75]
 [148.   151.7  147.1  150.5  150.65]
 [128.   129.   126.25 127.75 128.  ]
 ...
 [164.   169.9  161.55 168.3  167.7 ]
 [134.25 136.15 133.2  133.75 133.9 ]
 [147.   148.   144.2  146.5  146.2 ]]


In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :-1] = sc.fit_transform(X_train[:, :-1])
X_test[:, :-1] = sc.transform(X_test[:, :-1])

In [4]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [5]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 1.23e+03  1.90e+03]
 [ 1.02e+04  4.54e+03]
 [ 7.12e+03  8.24e+03]
 [ 4.51e+03  4.30e+03]
 [ 4.23e+03  2.18e+03]
 [ 5.30e+03  1.73e+03]
 [ 3.10e+03  4.11e+03]
 [ 2.30e+03  1.81e+03]
 [ 1.17e+04  9.93e+03]
 [ 7.43e+02  7.65e+02]
 [ 1.60e+04  5.58e+04]
 [ 9.94e+03  1.03e+04]
 [ 9.24e+03  7.16e+03]
 [ 1.91e+03  2.74e+03]
 [ 1.30e+03  8.74e+02]
 [ 7.58e+03  2.74e+03]
 [ 1.03e+04  6.86e+03]
 [ 1.98e+03  3.06e+03]
 [ 2.13e+03  4.12e+03]
 [ 8.95e+03  7.02e+03]
 [ 5.36e+03  3.45e+03]
 [ 2.10e+03  3.09e+03]
 [ 3.79e+03  3.70e+03]
 [ 3.60e+03  3.17e+03]
 [ 5.02e+03  7.01e+03]
 [ 3.90e+03  2.32e+03]
 [ 1.20e+04  8.57e+03]
 [ 6.40e+03  4.54e+03]
 [ 2.18e+03  1.71e+03]
 [ 3.99e+03  4.98e+03]
 [ 5.34e+03  6.00e+03]
 [-8.56e+03  7.11e+03]
 [ 4.23e+03  3.60e+03]
 [ 4.67e+03  7.05e+03]
 [ 1.16e+03  1.49e+03]
 [ 4.09e+03  4.60e+03]
 [ 2.49e+03  1.63e+03]
 [ 4.43e+03  3.59e+03]
 [ 5.11e+03  3.67e+03]
 [ 2.92e+03  2.84e+03]
 [ 5.22e+03  3.16e+03]
 [ 2.36e+03  1.64e+03]
 [ 1.07e+04  4.71e+03]
 [ 1.40e+04

In [6]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-3.0256660215103635