In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('NSE-TATA.csv')
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[208.   222.25 206.85 216.   215.15]
 [217.   218.6  205.9  210.25 209.2 ]
 [223.5  227.8  216.15 217.25 218.2 ]
 ...
 [156.   160.8  155.85 160.3  160.15]
 [155.7  158.2  154.15 155.3  155.55]
 [157.   157.8  155.2  155.8  155.8 ]]
[10062.83  7407.06  3815.79 ...  4978.8   3204.49  2688.94]


In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
print(X_train)

[[159.25 159.8  153.5  154.2  154.75]
 [148.   151.7  147.1  150.5  150.65]
 [128.   129.   126.25 127.75 128.  ]
 ...
 [164.   169.9  161.55 168.3  167.7 ]
 [134.25 136.15 133.2  133.75 133.9 ]
 [147.   148.   144.2  146.5  146.2 ]]


In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :-1] = sc.fit_transform(X_train[:, :-1])
X_test[:, :-1] = sc.transform(X_test[:, :-1])

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

In [5]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 1077.32  1901.94]
 [10451.69  4544.83]
 [10944.65  8238.83]
 [ 4673.62  4303.91]
 [ 3113.67  2178.49]
 [ 1409.59  1729.  ]
 [ 1689.46  4105.11]
 [ 1726.37  1811.73]
 [12441.6   9934.06]
 [ 1306.38   765.29]
 [13781.58 55755.08]
 [ 6263.64 10330.87]
 [ 7558.07  7162.35]
 [ 2726.13  2738.14]
 [ 2296.24   873.85]
 [ 8157.99  2742.84]
 [15156.74  6855.32]
 [ 1245.27  3060.59]
 [ 2685.5   4119.2 ]
 [11234.    7022.82]
 [ 5090.12  3454.22]
 [ 2929.38  3091.19]
 [ 5584.92  3695.01]
 [ 2391.82  3171.42]
 [ 3520.59  7005.22]
 [ 2249.38  2322.75]
 [16821.38  8566.75]
 [ 7519.46  4536.3 ]
 [ 3441.38  1714.3 ]
 [ 5866.72  4978.8 ]
 [ 4191.96  6001.16]
 [ 3800.48  7111.7 ]
 [ 6989.71  3600.42]
 [10181.55  7052.02]
 [ 1197.57  1487.76]
 [ 5868.82  4600.91]
 [ 3172.23  1633.27]
 [ 2397.39  3586.44]
 [ 4462.51  3674.2 ]
 [ 1027.27  2844.74]
 [ 3344.2   3157.09]
 [ 2421.92  1635.01]
 [ 7288.93  4706.54]
 [ 9471.22  5479.6 ]
 [ 1545.98  2444.39]
 [ 2595.19  2738.72]
 [ 5973.45  4118.57]
 [ 2027.36  2

In [6]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.400083457774686