In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('NSE-TATA.csv')
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[208.   222.25 206.85 216.   215.15]
 [217.   218.6  205.9  210.25 209.2 ]
 [223.5  227.8  216.15 217.25 218.2 ]
 ...
 [156.   160.8  155.85 160.3  160.15]
 [155.7  158.2  154.15 155.3  155.55]
 [157.   157.8  155.2  155.8  155.8 ]]
[10062.83  7407.06  3815.79 ...  4978.8   3204.49  2688.94]


In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
print(X_train)

[[159.25 159.8  153.5  154.2  154.75]
 [148.   151.7  147.1  150.5  150.65]
 [128.   129.   126.25 127.75 128.  ]
 ...
 [164.   169.9  161.55 168.3  167.7 ]
 [134.25 136.15 133.2  133.75 133.9 ]
 [147.   148.   144.2  146.5  146.2 ]]


In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :-1] = sc.fit_transform(X_train[:, :-1])
X_test[:, :-1] = sc.transform(X_test[:, :-1])

In [4]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [5]:
y_pred = regressor.predict(X_test)
print(y_pred)

[ 9.13934400e+02  8.91849220e+03  7.77204832e+03  4.65991453e+03
  2.52682024e+03  3.74033513e+03  3.77088525e+03  1.91179449e+03
  1.43138783e+04  8.95653168e+01  1.95047039e+04  1.01151115e+04
  6.62462304e+03  1.41130201e+03  1.18851501e+02  7.16818956e+03
  1.12661716e+04  1.86301786e+03  2.22407849e+03  1.34445577e+04
  4.56520735e+03  1.60690906e+03  4.14118382e+03  3.54978438e+03
  4.83460206e+03  3.95519955e+03  1.42449005e+04  4.88296757e+03
  1.61499712e+03  5.81629084e+03  7.15215174e+03  6.28452013e+03
  3.26386295e+03  1.12853900e+04  8.25146639e+02  3.94182266e+03
  2.29409846e+03  3.99960235e+03  6.76952305e+03  3.19420975e+03
  5.54875316e+03  2.83574583e+03  1.15191037e+04  1.26436469e+04
  1.57017226e+03  1.71241114e+03  7.02180849e+03  1.74102435e+03
  4.48001097e+03  6.51725547e+03  2.41034712e+03  3.19852462e+03
  1.41201202e+03  2.35255493e+03  5.36406126e+03  1.29452524e+03
  7.61034373e+02  5.53144189e+03  1.26083801e+03  1.82024356e+03
  1.34111246e+04  1.50972

In [6]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.5306980337516383