In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('NSE-TATA.csv')
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[208.   222.25 206.85 216.   215.15]
 [217.   218.6  205.9  210.25 209.2 ]
 [223.5  227.8  216.15 217.25 218.2 ]
 ...
 [156.   160.8  155.85 160.3  160.15]
 [155.7  158.2  154.15 155.3  155.55]
 [157.   157.8  155.2  155.8  155.8 ]]
[10062.83  7407.06  3815.79 ...  4978.8   3204.49  2688.94]


In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
print(X_train)

[[159.25 159.8  153.5  154.2  154.75]
 [148.   151.7  147.1  150.5  150.65]
 [128.   129.   126.25 127.75 128.  ]
 ...
 [164.   169.9  161.55 168.3  167.7 ]
 [134.25 136.15 133.2  133.75 133.9 ]
 [147.   148.   144.2  146.5  146.2 ]]


In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :-1] = sc.fit_transform(X_train[:, :-1])
X_test[:, :-1] = sc.transform(X_test[:, :-1])

In [4]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR()

In [5]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 3123.92  1901.94]
 [ 3288.76  4544.83]
 [ 3269.91  8238.83]
 [ 3144.73  4303.91]
 [ 3161.06  2178.49]
 [ 3135.72  1729.  ]
 [ 3136.77  4105.11]
 [ 3141.59  1811.73]
 [ 3277.13  9934.06]
 [ 3119.27   765.29]
 [ 3218.63 55755.08]
 [ 3177.88 10330.87]
 [ 3277.99  7162.35]
 [ 3147.1   2738.14]
 [ 3144.55   873.85]
 [ 3263.05  2742.84]
 [ 3334.9   6855.32]
 [ 3136.05  3060.59]
 [ 3142.71  4119.2 ]
 [ 3315.26  7022.82]
 [ 3241.19  3454.22]
 [ 3152.77  3091.19]
 [ 3165.61  3695.01]
 [ 3152.58  3171.42]
 [ 3141.88  7005.22]
 [ 3138.05  2322.75]
 [ 3290.04  8566.75]
 [ 3181.74  4536.3 ]
 [ 3143.59  1714.3 ]
 [ 3167.43  4978.8 ]
 [ 3157.88  6001.16]
 [ 3147.35  7111.7 ]
 [ 3183.46  3600.42]
 [ 3321.36  7052.02]
 [ 3122.81  1487.76]
 [ 3177.59  4600.91]
 [ 3143.59  1633.27]
 [ 3136.32  3586.44]
 [ 3174.15  3674.2 ]
 [ 3136.71  2844.74]
 [ 3143.3   3157.09]
 [ 3130.92  1635.01]
 [ 3303.48  4706.54]
 [ 3330.35  5479.6 ]
 [ 3122.85  2444.39]
 [ 3163.39  2738.72]
 [ 3238.34  4118.57]
 [ 3151.49  2

In [6]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.05591526680419956